# Generated by Django 5.2.1 on 2026-07-17 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('due_date', models.DateField(verbose_name='Due Date')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('commenter', models.CharField(verbose_name='accounts.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Lesson Name')),
                ('field_of_study', models.CharField(choices=[('MATH', 'Mathematics'), ('SCIENCE', 'Science'), ('HUMANITIES', 'Humanities')], verbose_name='Field of Study')),
                ('stage', models.CharField(choices=[('TENTH', 'Tenth Grade'), ('ELEVENTH', 'Eleventh Grade'), ('TWELFTH', 'Twelfth Grade'), ('GRADUATED', 'Graduated')], verbose_name='Stage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('file', models.FileField(upload_to='')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.exercise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.klass', verbose_name='Class'),
        ),
        migrations.CreateModel(
            name='KlassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.klass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KlassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')], default=0, verbose_name='Day of Week')),
                ('starts_at', models.TimeField(verbose_name='Starts At')),
                ('ends_at', models.TimeField(verbose_name='Ends At')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.klass', verbose_name='Class Schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='klass',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.lesson', verbose_name='Lesson'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='National Code')),
                ('field_of_study', models.CharField(choices=[('MATH', 'Mathematics'), ('SCIENCE', 'Science'), ('HUMANITIES', 'Humanities')], max_length=20, verbose_name='Field of Study')),
                ('stage', models.CharField(choices=[('TENTH', 'Tenth Grade'), ('ELEVENTH', 'Eleventh Grade'), ('TWELFTH', 'Twelfth Grade'), ('GRADUATED', 'Graduated')], max_length=20, verbose_name='Stage')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, verbose_name='Gender')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('supervisor_phone_number', models.CharField(max_length=15, verbose_name='Supervisor Phone Number')),
                ('province', models.CharField(max_length=50, verbose_name='Province')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('village', models.CharField(max_length=50, verbose_name='Village')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('postcode', models.CharField(max_length=10, verbose_name='Postcode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='klass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.teacher', verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='classes.teacher', verbose_name='Created By'),
        ),
        migrations.CreateModel(
            name='ExerciseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/%Y/%m/', verbose_name='File')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Grade')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Graded At')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='classes.exercise', verbose_name='Exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='classes.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Exercise Submission',
                'verbose_name_plural': 'Exercise Submissions',
                'unique_together': {('exercise', 'student')},
            },
        ),
    ]
