# Generated by Django 5.2.1 on 2026-07-19 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klassregistration',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='classes.student', verbose_name='Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='klassregistration',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='classes.klass', verbose_name='Class'),
        ),
    ]
