# Generated by Django 5.2.1 on 2025-08-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='', verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(choices=[('Science', 'Science'), ('Math', 'Math'), ('Humanities', 'Humanities')], default='', verbose_name='Field of Study'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='national_code',
            field=models.CharField(default='', verbose_name='National Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='', max_length=15, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='province',
            field=models.CharField(default='', verbose_name='Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.CharField(choices=[('Eleventh Year', 'Eleventh Year'), ('Twelfth Year', 'Twelfth Year')], default='', verbose_name='School Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='supervisor_phone_number',
            field=models.CharField(default='', max_length=15, verbose_name='Supervisor Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='village',
            field=models.CharField(blank=True, verbose_name='Village'),
        ),
    ]
