# Generated by Django 5.2.1 on 2026-07-19 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_exercisecomment_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
