# Generated by Django 5.2.1 on 2025-08-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_student_city_student_field_of_study_student_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='national_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='province',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='supervisor_phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='village',
        ),
    ]
