# Generated by Django 5.2.1 on 2026-08-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_exercisesubmission_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Lesson Name'),
        ),
    ]
