# Generated by Django 5.2.1 on 2025-08-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_student_city_remove_student_field_of_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(choices=[('MATH', 'Mathematics'), ('SCIENCE', 'Science'), ('HUMANITIES', 'Humanities')], default='', max_length=20, verbose_name='Field of Study'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='', max_length=10, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='national_code',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='National Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='', max_length=15, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='postcode',
            field=models.CharField(default='', max_length=10, verbose_name='Postcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='province',
            field=models.CharField(default='', max_length=50, verbose_name='Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stage',
            field=models.CharField(choices=[('TENTH', 'Tenth Grade'), ('ELEVENTH', 'Eleventh Grade'), ('TWELFTH', 'Twelfth Grade'), ('GRADUATED', 'Graduated')], default='', max_length=20, verbose_name='Stage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='supervisor_phone_number',
            field=models.CharField(default='', max_length=15, verbose_name='Supervisor Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='village',
            field=models.CharField(default='', max_length=50, verbose_name='Village'),
            preserve_default=False,
        ),
    ]
