# Generated by Django 5.2.1 on 2025-08-17 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_student_address_student_city_student_field_of_study_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='weekly_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classes.weeklyschedule', verbose_name='Weekly Schedule'),
        ),
    ]
