# Generated by Django 5.2.1 on 2026-08-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_lesson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
