# Generated by Django 5.2.1 on 2026-07-02 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_exercise_exercisesubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('session_date', models.DateField(verbose_name='Date')),
                ('starts_at', models.TimeField(verbose_name='Starts At')),
                ('ends_at', models.TimeField(verbose_name='Ends At')),
                ('capacity', models.PositiveIntegerField(default=20, verbose_name='Capacity')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Cancelled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='classes.teacher', verbose_name='Counselor')),
            ],
            options={
                'verbose_name': 'Counseling Session',
                'verbose_name_plural': 'Counseling Sessions',
                'ordering': ['session_date', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('exam_date', models.DateField(verbose_name='Exam Date')),
                ('starts_at', models.TimeField(verbose_name='Starts At')),
                ('total_score', models.PositiveSmallIntegerField(default=20, verbose_name='Total Score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='classes.teacher', verbose_name='Created By')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='classes.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['exam_date', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Handout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='handouts/%Y/%m/', verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handouts', to='classes.lesson', verbose_name='Lesson')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handouts', to='classes.teacher', verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Handout',
                'verbose_name_plural': 'Handouts',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CounselingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_registrations', to='classes.student', verbose_name='Student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='classes.counselingsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Counseling Registration',
                'verbose_name_plural': 'Counseling Registrations',
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score')),
                ('graded_at', models.DateTimeField(auto_now_add=True, verbose_name='Graded At')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='classes.exam', verbose_name='Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='classes.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
