# Generated by Django 5.2.1 on 2026-07-15 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_counselingsession_exam_handout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesubmission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Graded At'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('topic', models.CharField(max_length=200, verbose_name='Topic')),
                ('body', models.TextField(verbose_name='Body')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered')], default='pending', max_length=10, verbose_name='Status')),
                ('answer', models.TextField(blank=True, verbose_name='Answer')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Answered At')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to='classes.teacher', verbose_name='Answered By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='classes.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
