services:
  student-be:
    build: .
    environment:
      - DEBUG=True
      - SECRET=hello
      - ALLOWED_HOSTS=localhost
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000
    ports:
      - "8000:8000"
