{{- range .Values.persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  labels:
    {{- include "helmchart.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  {{- with .storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size }}
  {{- with .volumeName }}
  volumeName: {{ . }}
  {{- end }}
---
{{- end }}
