# Generated by Django 5.2.1 on 2025-06-07 21:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='National Code')),
                ('field_of_study', models.CharField(choices=[('MATH', 'Mathematics'), ('SCIENCE', 'Science'), ('HUMANITIES', 'Humanities')], max_length=20, verbose_name='Field of Study')),
                ('stage', models.CharField(choices=[('TENTH', 'Tenth Grade'), ('ELEVENTH', 'Eleventh Grade'), ('TWELFTH', 'Twelfth Grade'), ('GRADUATED', 'Graduated')], max_length=20, verbose_name='Stage')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'FEMALE')], max_length=10, verbose_name='Gender')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
                ('supervisor_phone_number', models.CharField(blank=True, max_length=15, verbose_name='Supervisor Phone Number')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='City')),
                ('village', models.CharField(blank=True, max_length=50, verbose_name='Village')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('postcode', models.CharField(blank=True, max_length=10, verbose_name='Postcode')),
                ('has_smartphone', models.BooleanField(default=False, verbose_name='Has Smartphone')),
                ('eager_to_join_english_class', models.BooleanField(default=False, verbose_name='Eager to Join English Class')),
                ('eager_to_join_book_club', models.BooleanField(default=False, verbose_name='Eager to Join Book Club')),
                ('eager_to_join_thinking_club', models.BooleanField(default=False, verbose_name='Eager to Join Thinking Class')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
