# Generated by Django 5.2.1 on 2025-08-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='eager_to_join_book_club',
        ),
        migrations.RemoveField(
            model_name='user',
            name='eager_to_join_english_class',
        ),
        migrations.RemoveField(
            model_name='user',
            name='eager_to_join_thinking_club',
        ),
        migrations.RemoveField(
            model_name='user',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_smartphone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='province',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='user',
            name='supervisor_phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='village',
        ),
    ]
