name: Build, push and deploy student frontend

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build image
        working-directory: student-fe
        run: docker build -f Dockerfile . -t ghcr.io/hojatm-huma/student-fe:${GITHUB_SHA::7}

      - name: push image
        run: docker push ghcr.io/hojatm-huma/student-fe:${GITHUB_SHA::7}

      - name: setup helm
        uses: azure/setup-helm@v5

      
      - name: setup kubeconfig
        run: |
          mkdir -p ./kube
          echo "${{ secrets.ARVAN_CLOUD_KUBECONFIG }}" | base64 --decode > ./kube/config

      - name: deploy
        run: |
          helm upgrade --install student-fe ./helmchart \
            --values student-fe/deploy/values.yaml \
            --set image.tag=${GITHUB_SHA::7}
